version: '3.8'
networks:
  api-network:
    driver: bridge

volumes:
  mongodb-vol:

services:

  api:
    image: igorcruz/api-produto:v1
    networks:
    - api-network
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongouser:secret@mongodb:27017/admin
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:5.0.3
    networks:
    - api-network
    volumes:
    - mongodb-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
